### ISSUE TITLE
Wrong link to the paper

### ISSUE THREAD

**Issue by sashulyak** [iNLyze/DeepLearning-SeGAN-Segmentation#5]
Hi!

I think, there is a mistake in the README. You put the link to the paper [SeGAN: Segmenting and Generating the Invisible](https://arxiv.org/pdf/1703.10239.pdf), but this repo is actually the implementation of [SegAN: Adversarial Network with Multi-scale L1 Loss for Medical
Image Segmentation](https://arxiv.org/pdf/1706.01805.pdf).

**Comment by iNLyze** [comment]
Thanks. Changing it.
