### ISSUE TITLE
 model Compile error

### ISSUE THREAD

**Issue by lokeshkvn** [iNLyze/DeepLearning-SeGAN-Segmentation#6]
in train
    self.rl.append(self.model.layers[-1].train_on_batch(X, y)) # Train critic

  File "envs\tensorflow\lib\site-packages\keras\engine\training.py", line 1209, in train_on_batch
    class_weight=class_weight)

  File "\envs\tensorflow\lib\site-packages\keras\engine\training.py", line 675, in _standardize_user_data
    raise RuntimeError('You must compile a model before '

RuntimeError: You must compile a model before training/testing. Use `model.compile(optimizer, loss)`.

**Comment by lokeshkvn** [comment]
No, I am just using the SeGAN model.

**Comment by Swati707** [comment]
You will have to compile all the models before training them, so that the models are configured with the appropriate loss and optimizer.

**Comment by lokeshkvn** [comment]
Thank you !
